### ISSUE TITLE
Broken vehicles, taxi and truck jobs due to recent change

### ISSUE THREAD

**Issue by iceeburr** [Hebei-Studios/Tang-County-Issues#4]
### Description

Due to a recent change in the car chassis module it introduced many side effects breaking some cars and jobs.

### Reproduction Steps

1. Spawn affected car/go to any driving job
2. Try to drive/start the job
3. Car tries to drive and makes sound, but stays in place/job not starting

### Screenshots & Videos

![image](https://github.com/Hebei-Studios/Tang-County-Issues/assets/85520957/95cf5bf9-93f9-4a63-9e97-378ccfa25939)
![image](https://github.com/Hebei-Studios/Tang-County-Issues/assets/85520957/6ca3b196-f7b9-47cc-83e6-eaee46eda4a6)
![image](https://github.com/Hebei-Studios/Tang-County-Issues/assets/85520957/7bceb9be-b268-47ad-abc7-4c1277b5b4d3)

### Logs

![image](https://github.com/Hebei-Studios/Tang-County-Issues/assets/85520957/d9226f14-962d-420d-b10e-fe1340ec7c12)

### Additional Information

Issue should be resolved in latest versions of the game, but we are still monitoring if the issue will persist.

### Checklist

- [X] Reproduced the issue at least once.
- [X] Attached valid error logs.
- [X] Included screenshots of the bug happening.

**Comment by SolarFolix** [comment]
- Fixed it because there 2 initialize inside both car in Taxi Job run on server

**Comment by iceeburr** [comment]
Many players have reported that the truck job is still broken. We need to monitor this further and implement needed patches.
![image](https://github.com/Hebei-Studios/Tang-County-Issues/assets/85520957/7d5c78f8-5c41-4dad-8bf7-9433d81d278a)

**Comment by iceeburr** [comment]
Confirmed that the taxi and trucker jobs persist on the latest version. Will be looked into.
